version: "3.9"
services:
  rabbit:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]
    environment:
      hostname: localhost
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  mongodb:
    image: mongo:7
    ports: ["27017:27017"]
  # Microservices will be added here or run from IDE
networks:
  default:
    name: insighthub
