apiVersion: v1
kind: Service
metadata:
  name: upload-clean
  namespace: insighthub
spec:
  selector:
    app: upload-clean
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-clean
  namespace: insighthub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-clean
  template:
    metadata:
      labels:
        app: upload-clean
    spec:
      containers:
        - name: upload-clean
          image: ranjeetjena06/upload-clean-service:d1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/auto_clean"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbit"
            - name: SERVER_PORT
              value: "8081"
            - name: APP_UPLOAD_DIR
              value: "/app/uploads"
            - name: APP_CLEAN_DIR
              value: "/app/cleaned"
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
            - name: cleaned
              mountPath: /app/cleaned
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc
        - name: cleaned
          persistentVolumeClaim:
            claimName: cleaned-pvc
