apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data/uploads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cleaned-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data/cleaned
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reports-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data/reports
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: insighthub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleaned-pvc
  namespace: insighthub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-pvc
  namespace: insighthub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
