spring:
  application:
    name: report
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

report:
  rabbitmq:
    queue: report-data-queue
    exchange: report-exchange
    routing-key: report.routing.key

app:
  report:
    dir: /app/reports

server:
  port: 8083
